apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: zipkin
  namespace: team5
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: zipkin
    spec:
      restartPolicy: Always
      containers:
      - env:
        image: openzipkin/zipkin
        name: zipkin
        ports:
        - containerPort: 9411
        - containerPort: 9410
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9411
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 9411
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
