kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis
  namespace: team5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard